version: '3'

services:
  backend:
    build:
      context: ./Backend/iSnippets
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: isinppets_db
      MYSQL_USER: sandy
      MYSQL_PASSWORD: sandy2508
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql

